version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: userdb
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: micro-userdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdminUI
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: salved34@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

  springboot:
    build: .
    container_name: micro-userservice
    environment:
      SERVER_PORT: 9092
      SPRING_DATASOURCE_USER: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/micro-userdb
    ports:
      - "9092:9092"

volumes:
 postgres_data:
